AWSTemplateFormatVersion: 2010-09-09
Description: This stack deploys a Module specific IAM permissions

Parameters:
  ProjectName:
    Type: String
    Description: The name of the project
  RoleName:
    Type: String
    Description: The name of the IAM Role
  HelmDistroSecretName:
    Type: String
    Description: The name of the AWS Secret for the Helm Distro
    Default: ""
  HostedRepoSecretName:
    Type: String
    Description: The name of the AWS Secret for the Hosted Repo
    Default: ""

Conditions:
  HasHelmDistroSecretName: !Not [!Equals [!Ref HelmDistroSecretName, ""]]
  HasHostedRepoSecretName: !Not [!Equals [!Ref HostedRepoSecretName, ""]]

Resources:
  Policy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - "ecr:Describe*"
              - "ecr:Get*"
              - "ecr:List*"
            Resource: "*"
          - Action:
              - "ecr:Create*"
              - "ecr:Delete*"
              - "ecr:*LayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:Batch*"
              - "ecr:Put*"
            Effect: Allow
            Resource:
              - !Sub "arn:${AWS::Partition}:ecr:${AWS::Region}:${AWS::AccountId}:repository/${ProjectName}-*"
          - Action:
              - "s3:CreateBucket"
            Effect: Allow
            Resource: "*"
          - Action:
              - "s3:ListBucket"
              - "s3:PutObject"
            Effect: Allow
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::*-d*-rep*-*"
          - Action:
              - "s3:CreateBucket"
              - "s3:ListBucket"
              - "s3:PutObject"
            Effect: Allow
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::*-d*-rep*-*/*"
          - !If 
            - HasHelmDistroSecretName
            - 
              Effect: Allow
              Sid: HelmRepoSecretsManager
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
              Resource:
                - Fn::Sub: "arn:${AWS::Partition}:secretsmanager:*:${AWS::AccountId}:secret:${HelmDistroSecretName}*"
            - !Ref AWS::NoValue
          - !If 
            - HasHostedRepoSecretName
            - 
              Effect: Allow
              Sid: HostedRepoSecretsManager
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
              Resource:
                - Fn::Sub: "arn:${AWS::Partition}:secretsmanager:*:${AWS::AccountId}:secret:${HostedRepoSecretName}*"
            - !Ref AWS::NoValue
            
        Version: 2012-10-17
      PolicyName: "modulespecific-policy"
      Roles: [!Ref RoleName]