AWSTemplateFormatVersion: 2010-09-09
Description: This template deploys a Module specific IAM permissions

Parameters:
  # ProjectName:
  #   Type: String
  #   Description: The name of the project
  # DeploymentName:
  #   Type: String
  #   Description: The name of the deployment
  # ModuleName:
  #   Type: String
  #   Description: The name of the Module
  RoleName:
    Type: String
    Description: The name of the IAM Role

Resources:
  Policy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - "cloudformation:List*"
              - "servicecatalog:Get*"
            Effect: Allow
            Resource: "*"
          - Action:
              - "servicecatalog:AssociateResource"
              - "servicecatalog:DisassociateResource"
            Effect: Allow
            Resource:
               - !Sub "arn:${AWS::Partition}:servicecatalog:${AWS::Region}:${AWS::AccountId}:/applications/*"
        Version: 2012-10-17
      PolicyName: idf-modulespecific-policy
      Roles: [!Ref RoleName]