AWSTemplateFormatVersion: "2010-09-09"
Description: This stack deploys a Module specific IAM permissions

Parameters:
  RoleName:
    Type: String
    Description: The name of the IAM Role

Resources:
  Policy:
    Type: "AWS::IAM::Policy"
    Properties:
      Roles:
        - !Ref RoleName
      PolicyName: idf-modulespecific-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # Wildcard use on the specfic resources created by seedfarmer
          - Effect: Allow
            Action:
              - iam:CreateServiceLinkedRole
            Resource:
              - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/aws-service-role/*
