name: neptune
path: modules/database/neptune
parameters:
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: networking
        name: basic-networking
        key: VpcId
  - name: private-subnet-ids
    valueFrom:
      moduleMetadata:
        group: networking
        name: basic-networking
        key: PrivateSubnetIds
  - name: number-instances
    value: 1
---
name: mysql
path: modules/database/rds
targetAccount: primary
parameters:
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: networking
        name: basic-networking
        key: VpcId
  - name: subnet-ids
    valueFrom:
      moduleMetadata:
        group: networking
        name: basic-networking
        key: PrivateSubnetIds
  - name: engine
    value: mysql
  - name: admin-username
    value: admin
  - name: instance-type
    value: t2.small
  - name: removal-policy
    value: DESTROY
