name: neptune
path: modules/database/neptune
parameters:
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: networking
        name: basic-networking
        key: VpcId
  - name: private-subnet-ids
    valueFrom:
      moduleMetadata:
        group: networking
        name: basic-networking
        key: PrivateSubnetIds
  - name: number-instances
    value: 1
---
name: mysql
path: modules/database/rds
targetAccount: primary
parameters:
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: networking
        name: basic-networking
        key: VpcId
  - name: subnet-ids
    valueFrom:
      moduleMetadata:
        group: networking
        name: basic-networking
        key: PrivateSubnetIds
  - name: database-name
    value: test
  - name: engine
    value: mysql
  - name: engine-version
    value: 8.0.35
  - name: instance-type
    value: t3.small
  - name: admin-username
    value: admin
  - name: credential-rotation-days
    value: 90
  - name: removal-policy
    value: DESTROY
---
name: postgresql
path: modules/database/rds
targetAccount: primary
parameters:
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: networking
        name: basic-networking
        key: VpcId
  - name: subnet-ids
    valueFrom:
      moduleMetadata:
        group: networking
        name: basic-networking
        key: PrivateSubnetIds
  - name: database-name
    value: test
  - name: engine
    value: postgresql
  - name: engine-version
    value: 16.1
  - name: instance-type
    value: m6gd.large
  - name: admin-username
    value: postgres
  - name: credential-rotation-days
    value: 90
  - name: removal-policy
    value: DESTROY
