name: Check Modules for Integration Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  get-modules:
    name: Get Modules
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-modules.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get modules
        id: get-modules
        run: |
          set -x
          # Get all modules
          MODULES=()
          MODULES_WITHOUT_INTEG=()
          for d in modules/*/* ; do
              echo $d
              MODULES+=("$d")
          done
          for m in $MODULES ; do
              echo modules/${m}/integ/
              if [ ! -d ${m}/integ/ ]; then
                echo "No Integration tests for ${m}"
                MODULES_WITHOUT_INTEG+=($m)
              fi
          done
          # Create our json structure [{"module_path": "..."}]
          MODULES_JSON=$(echo "$MODULES_WITHOUT_INTEG" | jq -R -s 'split("\n")' | jq '[ .[] | select(length > 0) ]' | jq 'map({"module_name": .})')
          # Export the modules as json to the outputs
          echo 'matrix<<EOF' >> $GITHUB_OUTPUT
          echo $MODULES_JSON >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

  create-issues:
    name: Create issue for ${{ matrix.modules.module_path }}
    needs: get-modules
    strategy:
      fail-fast: false
      matrix:
        modules: ${{ fromJson(needs.get-modules.outputs.matrix) }}
        python-version: [3.9]
    runs-on: ubuntu-latest
    env:
      MODULE_PATH: ${{ matrix.modules.module_name }}
    steps:
      - name: placeholder
        run: |
          set -x
          echo $MODULE_PATH